# Generated by Django 4.1.5 on 2023-02-02 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultorias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='companyClient',
        ),
    ]
