# Generated by Django 4.1.5 on 2023-02-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultorias', '0004_adsclient_ads_client_date_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsclient',
            name='ads_client_type_investment',
            field=models.CharField(choices=[('Main Page Logo Mention', 'Main Page Logo Mention'), ('Sponsored Video', 'Sponsored Video'), ('Sponsored Post', 'Sponsored Post')], default='Sponsored Post', max_length=40),
        ),
    ]
