# Generated by Django 4.1.5 on 2023-02-20 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Consultorias', '0006_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('mentor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
