# Generated by Django 4.1.5 on 2023-02-20 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Consultorias', '0007_imagementor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagementor',
            name='mentor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultorias.mentor'),
        ),
    ]
