# Generated by Django 4.1.5 on 2023-02-20 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultorias', '0008_alter_imagementor_mentor_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageMentor',
        ),
    ]
