# Generated by Django 4.1.5 on 2023-02-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultorias', '0009_delete_imagementor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='mentor_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
