# Generated by Django 4.1.5 on 2023-02-20 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Consultorias', '0011_remove_mentor_mentor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultorias.mentor')),
            ],
        ),
    ]
