# Generated by Django 4.1.5 on 2023-02-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultorias', '0012_mentorimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentorImage',
        ),
    ]
